version: "3.9"
services:
  app:
    build:
      context: .
      args:
        RUNTIME: ${RUNTIME}
    env_file: .env
    ports:
      - "${PORT:-3000}:3000"  # fallback to 3000
    environment:
      - RUNTIME=${RUNTIME}
    networks:
      - app-network
    volumes:
      - .:/app

networks:
  app-network:
    driver: bridge
