# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2025-05-29T23:39:53+00:00

from __future__ import annotations

from datetime import date, time
from typing import List

from pydantic import BaseModel, Field, constr


class Item(BaseModel):
    shortDescription: constr(regex=r'^[\w\s\-]+$') = Field(
        ...,
        description='The Short Product Description for the item.',
        example='Mountain Dew 12PK',
    )
    price: constr(regex=r'^\d+\.\d{2}$') = Field(
        ..., description='The total price payed for this item.', example='6.49'
    )


class Receipt(BaseModel):
    retailer: constr(regex=r'^[\w\s\-&]+$') = Field(
        ...,
        description='The name of the retailer or store the receipt is from.',
        example='M&M Corner Market',
    )
    purchaseDate: date = Field(
        ...,
        description='The date of the purchase printed on the receipt.',
        example='2022-01-01',
    )
    purchaseTime: time = Field(
        ...,
        description='The time of the purchase printed on the receipt. 24-hour time expected.',
        example='13:01',
    )
    items: List[Item] = Field(..., min_items=1)
    total: constr(regex=r'^\d+\.\d{2}$') = Field(
        ..., description='The total amount paid on the receipt.', example='6.49'
    )
