# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2025-05-29T23:39:53+00:00

from datetime import date, time
# Pattern needs to be imported from typing for Pydantic to recognize it
# correctly in the Field pattern argument.
from typing import List, Pattern

from pydantic import BaseModel, Field, ConfigDict

class Item(BaseModel):
  short_description: str = Field(
    ...,
    description='The Short Product Description for the item.',
    pattern=r'^[\w\s\-]+$',
    alias='shortDescription',
    json_schema_extra={
      "example": "Mountain Dew 12PK"
    }
  )
  price: str = Field(
    ...,
    description='The total price payed for this item.',
    pattern=r'^\d+\.\d{2}$',
    json_schema_extra={"example": "6.49"}
  )
  model_config = ConfigDict(populate_by_name=True)


class Receipt(BaseModel):
  retailer: str = Field(
    ...,
    description='The name of the retailer or store the receipt is from.',
    pattern=r'^[\w\s\-&]+$',
    json_schema_extra={"example": "M&M Corner Market"}
  )
  purchase_date: date = Field(
    ...,
    description='The date of the purchase printed on the receipt.',
    alias='purchaseDate',
    json_schema_extra={"example": "2022-01-01"}
  )
  purchase_time: time = Field(
    ...,
    description='The time of the purchase printed on the receipt. 24-hour time expected.',
    alias='purchaseTime',
    json_schema_extra={"example": "13:01"}
  )
  items: List[Item] = Field(..., min_length=1)
  total: str = Field(
    ...,
    description='The total amount paid on the receipt.',
    pattern=r'^\d+\.\d{2}$',
    json_schema_extra={"example": "6.49"}
  )
  model_config = ConfigDict(populate_by_name=True)

class ReceiptProcessResponse(BaseModel):
  id: str = Field(
    ...,
    description='The ID assigned to the receipt.',
    pattern=r'^\S+$',
    json_schema_extra={"example": "adb6b560-0eef-42bc-9d16-df48f30e89b2"}
  )

class ReceiptPointResponse(BaseModel):
  points: int = Field(
    ...,
    description='The number of points awarded.',
    json_schema_extra={"example": 100}
  )