# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2025-05-29T23:39:53+00:00

from datetime import date, time
# Pattern needs to be imported from typing for Pydantic to recognize it
# correctly in the Field pattern argument.
from typing import List, Pattern

from pydantic import BaseModel, Field, ConfigDict

class Item(BaseModel):
  """
  Represents an item with a short description and price.
  Attributes:
    short_description (str): The Short Product Description for the item.
      - Must match the pattern: ^[\w\s\-]+$
      - Example: "Mountain Dew 12PK"
      - Alias: 'shortDescription'
    price (str): The total price paid for this item.
      - Must match the pattern: ^\d+\.\d{2}$
      - Example: "6.49"
  """

  short_description: str = Field(
    ...,
    description='The Short Product Description for the item.',
    pattern=r'^[\w\s\-]+$',
    alias='shortDescription',
    json_schema_extra={
      "example": "Mountain Dew 12PK"
    }
  )
  price: str = Field(
    ...,
    description='The total price payed for this item.',
    pattern=r'^\d+\.\d{2}$',
    json_schema_extra={"example": "6.49"}
  )
  model_config = ConfigDict(populate_by_name=True)


class Receipt(BaseModel):
  """
  Represents a purchase receipt with details about the retailer, purchase date and time, items bought, and total amount.
  Attributes:
    retailer (str): The name of the retailer or store the receipt is from. Must match the pattern '^[\w\s\-&]+$'.
    purchase_date (date): The date of the purchase printed on the receipt. Uses the alias 'purchaseDate'.
    purchase_time (time): The time of the purchase printed on the receipt in 24-hour format. Uses the alias 'purchaseTime'.
    items (List[Item]): A list of items purchased. Must contain at least one item.
    total (str): The total amount paid on the receipt, formatted as a string with two decimal places (e.g., "6.49").
  """

  retailer: str = Field(
    ...,
    description='The name of the retailer or store the receipt is from.',
    pattern=r'^[\w\s\-&]+$',
    json_schema_extra={"example": "M&M Corner Market"}
  )
  purchase_date: date = Field(
    ...,
    description='The date of the purchase printed on the receipt.',
    alias='purchaseDate',
    json_schema_extra={"example": "2022-01-01"}
  )
  purchase_time: time = Field(
    ...,
    description='The time of the purchase printed on the receipt. 24-hour time expected.',
    alias='purchaseTime',
    json_schema_extra={"example": "13:01"}
  )
  items: List[Item] = Field(..., min_length=1)
  total: str = Field(
    ...,
    description='The total amount paid on the receipt.',
    pattern=r'^\d+\.\d{2}$',
    json_schema_extra={"example": "6.49"}
  )
  model_config = ConfigDict(populate_by_name=True)

class ReceiptProcessResponse(BaseModel):
  """
  Response model representing the result of processing a receipt.
  Attributes:
    id (str): The ID assigned to the receipt. Must be a non-whitespace string.
      Example: "adb6b560-0eef-42bc-9d16-df48f30e89b2"
  """

  id: str = Field(
    ...,
    description='The ID assigned to the receipt.',
    pattern=r'^\S+$',
    json_schema_extra={"example": "adb6b560-0eef-42bc-9d16-df48f30e89b2"}
  )

class ReceiptPointResponse(BaseModel):
  """
  Represents the response model for receipt points.
  Attributes:
    points (int): The number of points awarded. Example: 100.
  """

  points: int = Field(
    ...,
    description='The number of points awarded.',
    json_schema_extra={"example": 100}
  )